remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: www.cali.run
logo: http://cali.run/assets/img/logo.png
description: ğ‘ªğ’“ğ’†ğ’‚ğ’•ğ’Šğ’—ğ’Šğ’•ğ’š ğ’–. ğ‘¹ğ’†ğ’‚ğ’”ğ’ğ’ ğ‘ğ‘Ÿğ‘’ ğ‘‡ğ‘’ğ‘Ÿğ‘Ÿğ‘–ğ‘ğ‘™ğ‘’ ğ‘ƒğ‘ğ‘Ÿğ‘¡ğ‘›ğ‘’ğ‘Ÿğ‘ 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
